# Generated by Django 3.0.8 on 2020-07-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetterCotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=50)),
                ('cotation', models.FloatField()),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(default=0)),
                ('type_coin', models.CharField(max_length=5)),
                ('coin_name', models.CharField(max_length=50)),
                ('buy_real_cotation', models.FloatField()),
                ('sale_real_cotation', models.FloatField()),
                ('buy_dolar_cotation', models.FloatField()),
                ('sale_dolar_cotation', models.FloatField()),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
